apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.cassandraAuthSecret" . }}
  namespace: default
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
  labels:
    {{- include "service.labels" . | nindent 4 }}
stringData:
  username: {{ include "service.keyspace" . }}
