apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-{{ include "service.name" . }}-files
  namespace: default
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "0"
  labels:
    {{- include "service.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
